import { useMemo, useState } from "react";
import { activities } from "../data/activities";
import { decryptSession, generateProtectedKeyPair, readHeader, unlockPrivateKey } from "../lib/crypto";
import { downloadBlob, safeFilename } from "../lib/download";
import type { LabSession } from "../types";

const downloadText=(value:string,name:string,type="application/json")=>downloadBlob(new Blob([value],{type}),name);

export function ProfessorViewer(){
  const [labFiles,setLabFiles]=useState<File[]>([]),[keyFile,setKeyFile]=useState<File|null>(null),[password,setPassword]=useState(""),[sessions,setSessions]=useState<LabSession[]>([]),[message,setMessage]=useState(""),[selected,setSelected]=useState(0),[keyPassword,setKeyPassword]=useState("");
  const importFiles=(files:FileList|null)=>{const valid=[...(files??[])].filter(file=>file.size<=10_000_000&&file.name.endsWith(".rglab"));setLabFiles(valid);setMessage(valid.length?`${valid.length} arquivo(s) pronto(s).`:"Selecione arquivos .rglab de até 10 MB.")};
  const decrypt=async()=>{if(!keyFile||!labFiles.length)return;setMessage("Validando e descriptografando…");try{const unlocked=await unlockPrivateKey(await keyFile.arrayBuffer(),password);const results:LabSession[]=[];for(const file of labFiles){const buffer=await file.arrayBuffer();const header=readHeader(buffer).header;if(header.keyId!==unlocked.keyId)throw new Error(`A chave ${unlocked.keyId} não corresponde ao arquivo (${header.keyId}).`);results.push(await decryptSession(buffer,unlocked.key));}setSessions(results);setSelected(0);setMessage(`${results.length} sessão(ões) autenticada(s).`)}catch(error){setSessions([]);setMessage(error instanceof Error?error.message:"Falha ao abrir os arquivos.")}};
  const classStats=useMemo(()=>{if(!sessions.length)return null;const all=sessions.map(session=>session.summary).filter(Boolean);const avg=(selector:(summary:NonNullable<LabSession["summary"]>)=>number)=>all.reduce((total,item)=>total+selector(item!),0)/all.length;const errorCount=activities.map((_,index)=>sessions.reduce((total,session)=>total+session.activities[index].questions.filter(attempt=>!attempt.correct).length,0));const restartCount=activities.map((_,index)=>sessions.reduce((total,session)=>total+session.activities[index].restarts,0));return{score:avg(s=>s.score),time:sessions.reduce((total,s)=>total+(s.totalDurationMs??0),0)/sessions.length,errorActivity:errorCount.indexOf(Math.max(...errorCount)),restartActivity:restartCount.indexOf(Math.max(...restartCount)),continued:100*sessions.filter(s=>s.activities.some(r=>r.continuedAfterError)).length/sessions.length}},[sessions]);
  const generateKeys=async()=>{try{const generated=await generateProtectedKeyPair(keyPassword);downloadBlob(generated.protectedPrivateKey,`professor-${generated.keyId}.rglabkey`);downloadText(JSON.stringify({keyId:generated.keyId,publicKey:generated.publicKey},null,2),`publica-${generated.keyId}.json`);setMessage("Par gerado. Guarde a chave privada e sua senha em local seguro.")}catch(error){setMessage(error instanceof Error?error.message:"Falha ao gerar chaves.")}};
  const exportCsv=()=>{const rows=["sessionId,nome,matricula,turma,pontuacao,tempoMin,erros,pistas,refacoes",...sessions.map(s=>[s.sessionId,JSON.stringify(s.student.name),s.student.registration??"",s.student.className??"",s.summary?.score??0,((s.totalDurationMs??0)/60000).toFixed(1),s.summary?.errors??0,s.summary?.hints??0,s.summary?.restarts??0].join(","))];downloadText(rows.join("\n"),"turma-rg-lab.csv","text/csv")};
  const reportPdf=async(session:LabSession)=>{const {createSessionPdf}=await import("../lib/pdf");downloadBlob(createSessionPdf(session),`relatorio-${safeFilename(session.student.name)}.pdf`)};
  const current=sessions[selected];
  return <main className="professor-page"><header className="professor-hero"><div><p className="eyebrow">Interface local · dados não são transmitidos</p><h1>Professor <em>Viewer</em></h1><p>Abra, autentique e compare percursos do RG Interactive Lab.</p></div><div className="security-seal"><span>◈</span><strong>Processamento local</strong><small>A chave privada permanece neste navegador durante a operação.</small></div></header><section className="viewer-workbench"><article><span className="step-number">01</span><h2>Arquivos dos alunos</h2><label className="drop-zone">Selecionar arquivos .rglab<input type="file" accept=".rglab" multiple onChange={event=>importFiles(event.target.files)}/><small>{labFiles.length?labFiles.map(file=>file.name).join(" · "):"até 10 MB por arquivo"}</small></label></article><article><span className="step-number">02</span><h2>Chave do professor</h2><label className="file-field">Chave privada .rglabkey<input type="file" accept=".rglabkey" onChange={event=>setKeyFile(event.target.files?.[0]??null)}/></label><label className="password-field">Senha<input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password"/></label><button className="primary-button" disabled={!labFiles.length||!keyFile||!password} onClick={()=>void decrypt()}>Descriptografar e validar</button></article></section><div className="viewer-message" role="status">{message}</div>
  {sessions.length>0&&classStats&&<><section className="class-overview"><header><div><p className="eyebrow">Visão da turma</p><h2>{sessions.length} aluno(s)</h2></div><div className="export-actions"><button onClick={exportCsv}>Exportar CSV</button><button onClick={()=>downloadText(JSON.stringify(sessions,null,2),"turma-rg-lab.json")}>Exportar JSON</button></div></header><div className="class-metrics"><article><small>Média de acertos</small><strong>{classStats.score.toFixed(1)}%</strong></article><article><small>Tempo médio</small><strong>{(classStats.time/60000).toFixed(0)} min</strong></article><article><small>Mais erros</small><strong>{activities[classStats.errorActivity]?.title}</strong></article><article><small>Mais refeita</small><strong>{activities[classStats.restartActivity]?.title}</strong></article><article><small>Avançaram após erro</small><strong>{classStats.continued.toFixed(0)}%</strong></article></div></section><section className="individual-view"><div className="student-list">{sessions.map((session,index)=><button key={session.sessionId} className={index===selected?"active":""} onClick={()=>setSelected(index)}><strong>{session.student.name}</strong><span>{session.summary?.score??0}% · {session.student.className??"sem turma"}</span></button>)}</div>{current&&<article className="student-report"><header><div><p className="eyebrow">Visão individual</p><h2>{current.student.name}</h2><span>{current.student.registration??"sem matrícula"} · {current.student.className??"sem turma"}</span></div><button onClick={()=>void reportPdf(current)}>Gerar relatório PDF</button></header><div className="timeline">{current.activities.map((record,index)=><div key={record.activityId}><i className={record.status}/><b>{String(index+1).padStart(2,"0")}</b><span><strong>{activities[index].title}</strong><small>{record.questions.length} tentativa(s), {record.hintsUsed} pista(s), {record.restarts} refação(ões)</small></span><em>{record.status}</em></div>)}</div></article>}</section></>}
  <section className="key-generator"><div><p className="eyebrow">Administração de chaves</p><h2>Gerar novo par localmente</h2><p>A chave privada será protegida por senha. Faça backup: arquivos antigos não podem ser recuperados se ela for perdida.</p></div><div><label>Nova senha da chave<input type="password" minLength={10} value={keyPassword} onChange={event=>setKeyPassword(event.target.value)} placeholder="mínimo de 10 caracteres"/></label><button className="secondary-button" disabled={keyPassword.length<10} onClick={()=>void generateKeys()}>Gerar chaves RSA-3072</button><small>Dois arquivos serão baixados: a chave privada protegida e a configuração pública.</small></div></section></main>;
}
