import { activities } from "../data/activities";
import { encryptSession } from "../lib/crypto";
import { downloadBlob, safeFilename } from "../lib/download";
import { useLabStore } from "../store";

export function Summary(){
  const session=useLabStore(state=>state.session); if(!session||!session.summary)return null; const summary=session.summary,filename=safeFilename(session.student.name);
  const pdf=async()=>{const {createSessionPdf}=await import("../lib/pdf");downloadBlob(createSessionPdf(session),`rg-lab-${filename}.pdf`)}; const encrypted=async()=>downloadBlob(await encryptSession(session),`rg-lab-${filename}.rglab`);
  return <main className="summary-page"><section className="summary-hero"><p className="eyebrow">Percurso concluído</p><h1>{summary.score}<span>%</span></h1><div><h2>{session.student.name}</h2><p>{summary.completed} de {activities.length} atividades percorridas</p></div></section><section className="summary-grid"><article className="score-card"><h2>Resumo geral</h2><div className="summary-numbers"><span><strong>{summary.correct}</strong>dominadas</span><span><strong>{summary.errors}</strong>erros</span><span><strong>{summary.hints}</strong>pistas</span><span><strong>{summary.restarts}</strong>refações</span></div><h3>Competências</h3><div className="competencies">{summary.competencies.map(item=>{const value=Math.round(100*item.earned/item.possible);return <div key={item.competency}><span>{item.competency}</span><i><b style={{width:`${value}%`}}/></i><strong>{value}%</strong></div>})}</div></article><article className="export-card"><p className="eyebrow">Entregar e guardar</p><h2>Exporte seu percurso</h2><p>O PDF é legível e adequado para impressão. O arquivo <code>.rglab</code> contém os metadados completos, criptografados para o professor.</p><button className="primary-button" onClick={()=>void pdf()}>Gerar PDF da atividade <span>↓</span></button><button className="secondary-button" onClick={()=>void encrypted()}>Salvar dados para o professor <span>↓</span></button><small>Criptografia AES-256-GCM + RSA-OAEP. Nenhum dado é transmitido.</small></article></section><section className="activity-table"><header><h2>Atividades</h2><span>Status final</span></header>{session.activities.map((record,index)=><div key={record.activityId}><b>{String(index+1).padStart(2,"0")}</b><span>{activities[index].title}</span><small>{record.questions.length} tentativa(s) · {record.hintsUsed} pista(s)</small><strong className={record.status}>{record.status==="completed"?"Dominada":record.status==="skipped_after_error"?"Avançou após erro":"Incompleta"}</strong></div>)}</section></main>;
}
